ripple:
  api: '@api_url'
  cloudinary: 'https://api.cloudinary.com/v1_1'
  googleMaps: 'https://maps.googleapis.com/maps/api'
  mapsApiKey: '@js_map_key'
  cloudName: 'ddj4jx8rq'
  version: '@app_version'


production:
  api: '@api_url'
  cloudinary: 'https://api.cloudinary.com/v1_1'
  googleMaps: 'https://maps.googleapis.com/maps/api'
  mapsApiKey: '@js_map_key'
  cloudName: 'ddj4jx8rq'
  version: '@app_version'

development:
  api: '@api_url'
  cloudinary: 'https://api.cloudinary.com/v1_1'
  googleMaps: 'https://maps.googleapis.com/maps/api'
  mapsApiKey: '@js_map_key'
  cloudName: 'ddj4jx8rq'
  version: '@app_version'
